server:
  port: 9090
  # 启用HTTPS
#  ssl:
#    key-store:
#    key-store-password:
#    key-password:


spring:
  # 可配置读取哪些sql脚本（schema.sql,data.sql默认不需要配置，可以配置其他名称的sql）
  datasource:
    schema:
    - schema.sql
    data:
    - data.sql
  profiles:
    active: prod

logging:
  path: /var/logs
  file: TacoCloud.log
  level:
    root : WARN
    org.springframework.security: DENUG

taco:
  orders:
    pageSize: 10
