spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacodb
    password: tacopassword
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    # Taco Cloud代码的日志级别为WARN
    taco : WARN



